### PR TITLE
(WIP) Dockerfile: Set QT_VERSION=5.9.4

### PR DESCRIPTION
**Pull request by gmacario**
**PLEASE DO NOT MERGE YET!**

My previous PR https://github.com/hadim/docker-qt/pull/2 was merged even it did not completely fix https://github.com/hadim/docker-qt/issues/1

Continue debugging `docker build .` after switching to latest LTS release of Qt (5.9.4 at the time of this writing)

### CODE REVIEW

**Comment by gmacario** [comment]
Result of `docker build .` on https://github.com/hadim/docker-qt/pull/3/commits/ebc8c8ed9d85335768ade4977f3fc9a5ad3c7987

```
gpmacario@nemo:~/github/gmacario/docker-qt (wip-update-qt-594)$ docker build .
Sending build context to Docker daemon  162.3kB
Step 1/21 : FROM alpine:3.7
 ---> 3fd9065eaf02
Step 2/21 : MAINTAINER Hadrien Mary <hadrien.mary@gmail.com>
 ---> Using cache
 ---> 8f4d5d89b06d
Step 3/21 : RUN apk update &&     apk upgrade &&     apk --update add         gcc g++ build-base cmake bash libstdc++ libxcb-dev icu-dev         openssl-dev linux-headers curl git libproc libxrender-dev libexecinfo-dev         libpng libpng-dev libjpeg-turbo libjpeg-turbo-dev icu-libs icu         mesa-gl mesa-dev freetype-dev sqlite-dev gstreamer gstreamer0.10-dev         libogg-dev libvorbis-dev libbz2 gperf bison ruby flex &&     rm -rf /var/cache/apk/*
 ---> Using cache
 ---> c5c452e5d8ab
Step 4/21 : ENV QT_VERSION_MAJOR 5.9
 ---> Using cache
 ---> 7995d8b11128
Step 5/21 : ENV QT_VERSION 5.9.4
 ---> Using cache
 ---> f01b71ae0063
...
Creating qmake...
Done.
Info: creating cache file /qtbase-opensource-src-5.9.4/.qmake.cache
ERROR: Invalid value given for boolean command line option 'sql-sqlite'.

ERROR: Unknown command line option '-no-pulseaudio'.
The command '/bin/sh -c curl -sSL $QT_BASE_SRC | tar xJ     && cd $QT_BASE_DIR     && bash ./configure --help     && bash ./configure -opensource -confirm-license -static -no-accessibility -qt-sql-sqlite -no-qml-debug        -no-harfbuzz -openssl-linked -qt-pcre -no-pulseaudio -no-alsa -no-dbus -nomake tools        -no-xkbcommon-evdev -no-xinput2 -no-xcb-xlib -no-glib -qt-xcb -no-compile-examples -nomake examples        -no-gif -qt-doubleconversion -no-gtk     && make install' returned a non-zero code: 3
gpmacario@nemo:~/github/gmacario/docker-qt (wip-update-qt-594)$
```

**Comment by hadim** [comment]
I just saw that: https://cloud.docker.com/app/hadim/repository/docker/hadim/docker-qt/builds/6a20940f-a607-4442-9ae7-88c0938afd38

Sorry I looked at it too quickly. Let me know when it's ready to merge.

**Comment by gmacario** [comment]
Docker build failure.
See https://hub.docker.com/r/gmacario/docker-qt/builds/bfr5hrzv5dfahuupd89vn2k/

**Comment by hadim** [comment]
Does it work locally for you?

**Comment by hadim** [comment]
One other possibility would also to switch from alpine to ubuntu.

**Comment by gmacario** [comment]
Googling for "undefined reference to backtrace" I found this:
https://github.com/openalpr/openalpr/issues/566

@hadim I agree, I should rebase on ubuntu

**Comment by gmacario** [comment]
Docker autobuild failure.
See https://hub.docker.com/r/gmacario/docker-qt/builds/bhrkvcuqyabevu3qwa4wsub/

**Comment by gmacario** [comment]
There seems to have been an issue with your Automated Build "gmacario/docker-qt" (VCS repository: gmacario/docker-qt) during the build step.
You can find more information on
https://hub.docker.com/r/gmacario/docker-qt/builds/baiyscvvzrdnn8mxy557cdt/

**Comment by gmacario** [comment]
Docker automated build started: https://hub.docker.com/r/gmacario/docker-qt/builds/bhe4kesmvat3ffxq6rybnfm/

**Comment by gmacario** [comment]
Docker automated build started:
https://hub.docker.com/r/gmacario/docker-qt/builds/bzumbgm9pwmpikp3vcrj3ce/

**Comment by gmacario** [comment]
Docker automated build successful:
https://github.com/hadim/docker-qt/pull/3

Closing PR, rebasing patch set and creating new PR https://github.com/hadim/docker-qt/pull/4

**Pull request closed without merging**
